### ISSUE TITLE
add it to the catalogue

### ISSUE THREAD

**Issue by Helias** [tbcstar/mod-high-risk-system#2]
you can add this module to the azerothcore catalogue just adding `azerothcore-module` in the github topic ;-)
https://www.azerothcore.org/catalogue.html#/home

**Comment by yuanf225** [comment]
I don't understand how to add the module to the directory, can you tell me the specific steps, thanks

**Comment by Helias** [comment]
<img width="1618" alt="image" src="https://user-images.githubusercontent.com/519778/190429560-fd20a43a-c5d9-4bf8-9077-bdba4353dda9.png">

- Go on your repository
- on the top right next to `About` click to the settings icon
- add a topic there and save the changs
- check the azerothcore catalogue with another browser or in incognito mode, or delete the cache of your browser and refresh

**Comment by yuanf225** [comment]
![image](https://user-images.githubusercontent.com/43561197/190530537-2925ea89-758c-4938-b9f0-972e1274721c.png)
I see, thanks, I've added

**Comment by Helias** [comment]
you have to add `azerothcore-module`

**Comment by yuanf225** [comment]
done
